CMS/Models/CaseModel.cs
using System;

namespace CMS.Models
{
    public class CaseModel
    {
        public int CaseId { get; set; }
        public string Details { get; set; }
        public DateTime FilingDate { get; set; }
        public string Agency { get; set; }
        public string DefendantName { get; set; }
        public string DefendantAddress { get; set; }
        public string Charges { get; set; }
    }
}

CMS/Models/DapperORM.cs
using Dapper;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;

namespace CMS.Models
{
    public static class DapperORM
    {
        private static string connectionString = @"Data Source=localhost;Initial Catalog=CMSDB;Integrated Security=True;";

        public static void ExecuteWithoutReturn(string procedureName, DynamicParameters param = null)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                sqlCon.Execute(procedureName, param, commandType: CommandType.StoredProcedure);
            }
        }

        public static IEnumerable<T> ReturnList<T>(string procedureName, DynamicParameters param = null)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                return sqlCon.Query<T>(procedureName, param, commandType: CommandType.StoredProcedure);
            }
        }
    }
}

CMS/Controllers/CaseController.cs
using CMS.Models;
using Dapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.Controllers
{
    public class CaseController : Controller
    {
        // GET: Case
        public ActionResult Index()
        {
            return View(DapperORM.ReturnList<CaseModel>("CaseViewAll"));
        }


        // ... /Employee/AddOrEdit - insert
        // ... /Employee/AddOrEdit/id
        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
            if (id == 0)
                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@CaseId", id);
                return View(DapperORM.ReturnList<CaseModel>("CaseViewById", param).FirstOrDefault<CaseModel>());
            }
                
           
        }

        [HttpPost]
        public ActionResult AddOrEdit(CaseModel caseModel)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@CaseId", caseModel.CaseId);
            param.Add("@Details", caseModel.Details);
            param.Add("@FilingDate", caseModel.FilingDate);
            param.Add("@Agency", caseModel.Agency);
            param.Add("@DefendantName", caseModel.DefendantName);
            param.Add("@DefendantAddress", caseModel.DefendantAddress);
            param.Add("@Charges", caseModel.Charges);
            DapperORM.ExecuteWithoutReturn("CaseAddOrEdit", param);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@CaseId", id);
            DapperORM.ExecuteWithoutReturn("CaseDeleteById", param);
            return RedirectToAction("Index");
        }
    }
}

CMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        
        
    }
}

CMS/Views/Case/AddOrEdit.cshtml
@model CMS.Models.CaseModel

@{
    ViewBag.Title = "AddOrEdit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CaseId)

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefendantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefendantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefendantName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefendantAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefendantAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefendantAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charges, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charges, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charges, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" style="background-color:tan" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CMS/Views/Case/Index.cshtml
@model IEnumerable<CMS.Models.CaseModel>

@{
    ViewBag.Title = "CMS - Stark County Clerk of Courts";
}

<h2>Clerk Of Courts Library</h2>

<p>
    <u>@Html.ActionLink("Create New Record", "AddOrEdit", "Case")</u>
</p>
<table class="table table-bordered">
    <tr>
        <th>
            Number
        </th>
        <th>
            Details
        </th>
        <th>
            Date Filed
        </th>
        <th>
            Agency
        </th>
        <th>
            Defendant's Name
        </th>
        <th>
            Defendant's Address
        </th>
        <th>
            Charges
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CaseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilingDate.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Agency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefendantName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefendantAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Charges)
            </td>
            <td>
                @Html.ActionLink("Edit", "AddOrEdit", new {     id=item.CaseId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.CaseId  })
            </td>
        </tr>
    }

</table>

CMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title The Project:</h2>


<p style="font-size:20px"><u><i>William "Coby" Kelly</i></u> is the creator of this Mini Case Management System. Technologies used include DapperORM, SQL, C#, and more. Stored Procedure SQL 
    files were created to relay information to and from the database. </p>

<body>
    
    
    
    
</body>

CMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Meet The Clerk</h2>
<h3><u>Contact Information:</u></h3>

<address>
    115 Central Plaza N # 101<br />
    Canton, OH 44702<br />
    <abbr title="Phone">Phone:</abbr>
    (330) 451-7801
</address>

<address>
    <strong>Stark County Clerk of Courts:</strong>   <a href="https://www.starkcountyohio.gov/clerk">https://www.starkcountyohio.gov/clerk</a><br />

</address>

CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index", "Case", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Case")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Stark County Clerk of Courts</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>